/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExchangesRouteImport } from './routes/exchanges'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GiftCardsRouteImport } from './routes/gift-cards'
import { Route as LegalQuestionnaireRouteImport } from './routes/legal-questionnaire'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SizeGuideRouteImport } from './routes/size-guide'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActivitiesRouteImport } from './routes/admin/activities'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminDiscountsRouteImport } from './routes/admin/discounts'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminNewsletterRouteImport } from './routes/admin/newsletter'
import { Route as AdminPasskeysRouteImport } from './routes/admin/passkeys'
import { Route as AdminPermanentWardrobeRouteImport } from './routes/admin/permanent-wardrobe'
import { Route as AdminShippingRouteImport } from './routes/admin/shipping'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as CollectionsSlugRouteImport } from './routes/collections/$slug'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopSlugRouteImport } from './routes/shop/$slug'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders/index'
import { Route as AccountOrdersIdRouteImport } from './routes/account/orders/$id'
import { Route as AdminCollectionsIndexRouteImport } from './routes/admin/collections/index'
import { Route as AdminCollectionsIdRouteImport } from './routes/admin/collections/$id'
import { Route as AdminCollectionsNewRouteImport } from './routes/admin/collections/new'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers/index'
import { Route as AdminCustomersIdRouteImport } from './routes/admin/customers/$id'
import { Route as AdminGiftCardsIndexRouteImport } from './routes/admin/gift-cards/index'
import { Route as AdminGiftCardsIdRouteImport } from './routes/admin/gift-cards/$id'
import { Route as AdminNotificationsGeneralRouteImport } from './routes/admin/notifications/general'
import { Route as AdminNotificationsRequestsRouteImport } from './routes/admin/notifications/requests'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminOrdersIdRouteImport } from './routes/admin/orders/$id'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminProductsIdRouteImport } from './routes/admin/products/$id'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangesRoute = ExchangesRouteImport.update({
  id: '/exchanges',
  path: '/exchanges',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCardsRoute = GiftCardsRouteImport.update({
  id: '/gift-cards',
  path: '/gift-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalQuestionnaireRoute = LegalQuestionnaireRouteImport.update({
  id: '/legal-questionnaire',
  path: '/legal-questionnaire',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeGuideRoute = SizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivitiesRoute = AdminActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsRoute = AdminDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPasskeysRoute = AdminPasskeysRouteImport.update({
  id: '/passkeys',
  path: '/passkeys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermanentWardrobeRoute = AdminPermanentWardrobeRouteImport.update({
  id: '/permanent-wardrobe',
  path: '/permanent-wardrobe',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AdminRoute,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersIdRoute = AccountOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AccountRoute,
} as any)
const AdminCollectionsIndexRoute = AdminCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsIdRoute = AdminCollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsNewRoute = AdminCollectionsNewRouteImport.update({
  id: '/collections/new',
  path: '/collections/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGiftCardsIndexRoute = AdminGiftCardsIndexRouteImport.update({
  id: '/gift-cards/',
  path: '/gift-cards/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGiftCardsIdRoute = AdminGiftCardsIdRouteImport.update({
  id: '/gift-cards/$id',
  path: '/gift-cards/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsGeneralRoute =
  AdminNotificationsGeneralRouteImport.update({
    id: '/notifications/general',
    path: '/notifications/general',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminNotificationsRequestsRoute =
  AdminNotificationsRequestsRouteImport.update({
    id: '/notifications/requests',
    path: '/notifications/requests',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/exchanges': typeof ExchangesRoute
  '/faq': typeof FaqRoute
  '/gift-cards': typeof GiftCardsRoute
  '/legal-questionnaire': typeof LegalQuestionnaireRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRouteWithChildren
  '/size-guide': typeof SizeGuideRoute
  '/wishlist': typeof WishlistRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/passkeys': typeof AdminPasskeysRoute
  '/admin/permanent-wardrobe': typeof AdminPermanentWardrobeRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/admin/collections/$id': typeof AdminCollectionsIdRoute
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/gift-cards/$id': typeof AdminGiftCardsIdRoute
  '/admin/notifications/general': typeof AdminNotificationsGeneralRoute
  '/admin/notifications/requests': typeof AdminNotificationsRequestsRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/admin/collections/': typeof AdminCollectionsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/gift-cards/': typeof AdminGiftCardsIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/exchanges': typeof ExchangesRoute
  '/faq': typeof FaqRoute
  '/gift-cards': typeof GiftCardsRoute
  '/legal-questionnaire': typeof LegalQuestionnaireRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/shipping': typeof ShippingRoute
  '/size-guide': typeof SizeGuideRoute
  '/wishlist': typeof WishlistRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/passkeys': typeof AdminPasskeysRoute
  '/admin/permanent-wardrobe': typeof AdminPermanentWardrobeRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin': typeof AdminIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/shop': typeof ShopIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/admin/collections/$id': typeof AdminCollectionsIdRoute
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/gift-cards/$id': typeof AdminGiftCardsIdRoute
  '/admin/notifications/general': typeof AdminNotificationsGeneralRoute
  '/admin/notifications/requests': typeof AdminNotificationsRequestsRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/account/orders': typeof AccountOrdersIndexRoute
  '/admin/collections': typeof AdminCollectionsIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/gift-cards': typeof AdminGiftCardsIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/exchanges': typeof ExchangesRoute
  '/faq': typeof FaqRoute
  '/gift-cards': typeof GiftCardsRoute
  '/legal-questionnaire': typeof LegalQuestionnaireRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRouteWithChildren
  '/size-guide': typeof SizeGuideRoute
  '/wishlist': typeof WishlistRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/passkeys': typeof AdminPasskeysRoute
  '/admin/permanent-wardrobe': typeof AdminPermanentWardrobeRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/admin/collections/$id': typeof AdminCollectionsIdRoute
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/gift-cards/$id': typeof AdminGiftCardsIdRoute
  '/admin/notifications/general': typeof AdminNotificationsGeneralRoute
  '/admin/notifications/requests': typeof AdminNotificationsRequestsRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/admin/collections/': typeof AdminCollectionsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/gift-cards/': typeof AdminGiftCardsIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/admin-login'
    | '/checkout'
    | '/contact'
    | '/exchanges'
    | '/faq'
    | '/gift-cards'
    | '/legal-questionnaire'
    | '/order-confirmed'
    | '/shipping'
    | '/shop'
    | '/size-guide'
    | '/wishlist'
    | '/admin/activities'
    | '/admin/audit'
    | '/admin/discounts'
    | '/admin/inventory'
    | '/admin/newsletter'
    | '/admin/passkeys'
    | '/admin/permanent-wardrobe'
    | '/admin/shipping'
    | '/collections/$slug'
    | '/shop/$slug'
    | '/admin/'
    | '/collections/'
    | '/shop/'
    | '/account/orders/$id'
    | '/admin/collections/$id'
    | '/admin/collections/new'
    | '/admin/customers/$id'
    | '/admin/gift-cards/$id'
    | '/admin/notifications/general'
    | '/admin/notifications/requests'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/account/orders/'
    | '/admin/collections/'
    | '/admin/customers/'
    | '/admin/gift-cards/'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin-login'
    | '/checkout'
    | '/contact'
    | '/exchanges'
    | '/faq'
    | '/gift-cards'
    | '/legal-questionnaire'
    | '/order-confirmed'
    | '/shipping'
    | '/size-guide'
    | '/wishlist'
    | '/admin/activities'
    | '/admin/audit'
    | '/admin/discounts'
    | '/admin/inventory'
    | '/admin/newsletter'
    | '/admin/passkeys'
    | '/admin/permanent-wardrobe'
    | '/admin/shipping'
    | '/collections/$slug'
    | '/shop/$slug'
    | '/admin'
    | '/collections'
    | '/shop'
    | '/account/orders/$id'
    | '/admin/collections/$id'
    | '/admin/collections/new'
    | '/admin/customers/$id'
    | '/admin/gift-cards/$id'
    | '/admin/notifications/general'
    | '/admin/notifications/requests'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/account/orders'
    | '/admin/collections'
    | '/admin/customers'
    | '/admin/gift-cards'
    | '/admin/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/admin-login'
    | '/checkout'
    | '/contact'
    | '/exchanges'
    | '/faq'
    | '/gift-cards'
    | '/legal-questionnaire'
    | '/order-confirmed'
    | '/shipping'
    | '/shop'
    | '/size-guide'
    | '/wishlist'
    | '/admin/activities'
    | '/admin/audit'
    | '/admin/discounts'
    | '/admin/inventory'
    | '/admin/newsletter'
    | '/admin/passkeys'
    | '/admin/permanent-wardrobe'
    | '/admin/shipping'
    | '/collections/$slug'
    | '/shop/$slug'
    | '/admin/'
    | '/collections/'
    | '/shop/'
    | '/account/orders/$id'
    | '/admin/collections/$id'
    | '/admin/collections/new'
    | '/admin/customers/$id'
    | '/admin/gift-cards/$id'
    | '/admin/notifications/general'
    | '/admin/notifications/requests'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/account/orders/'
    | '/admin/collections/'
    | '/admin/customers/'
    | '/admin/gift-cards/'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ExchangesRoute: typeof ExchangesRoute
  FaqRoute: typeof FaqRoute
  GiftCardsRoute: typeof GiftCardsRoute
  LegalQuestionnaireRoute: typeof LegalQuestionnaireRoute
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRouteWithChildren
  SizeGuideRoute: typeof SizeGuideRoute
  WishlistRoute: typeof WishlistRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchanges': {
      id: '/exchanges'
      path: '/exchanges'
      fullPath: '/exchanges'
      preLoaderRoute: typeof ExchangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-cards': {
      id: '/gift-cards'
      path: '/gift-cards'
      fullPath: '/gift-cards'
      preLoaderRoute: typeof GiftCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-questionnaire': {
      id: '/legal-questionnaire'
      path: '/legal-questionnaire'
      fullPath: '/legal-questionnaire'
      preLoaderRoute: typeof LegalQuestionnaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-guide': {
      id: '/size-guide'
      path: '/size-guide'
      fullPath: '/size-guide'
      preLoaderRoute: typeof SizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activities': {
      id: '/admin/activities'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminActivitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts': {
      id: '/admin/discounts'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminDiscountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/passkeys': {
      id: '/admin/passkeys'
      path: '/passkeys'
      fullPath: '/admin/passkeys'
      preLoaderRoute: typeof AdminPasskeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permanent-wardrobe': {
      id: '/admin/permanent-wardrobe'
      path: '/permanent-wardrobe'
      fullPath: '/admin/permanent-wardrobe'
      preLoaderRoute: typeof AdminPermanentWardrobeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders/$id': {
      id: '/account/orders/$id'
      path: '/orders/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AccountOrdersIdRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/collections/': {
      id: '/admin/collections/'
      path: '/collections'
      fullPath: '/admin/collections/'
      preLoaderRoute: typeof AdminCollectionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections/$id': {
      id: '/admin/collections/$id'
      path: '/collections/$id'
      fullPath: '/admin/collections/$id'
      preLoaderRoute: typeof AdminCollectionsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections/new': {
      id: '/admin/collections/new'
      path: '/collections/new'
      fullPath: '/admin/collections/new'
      preLoaderRoute: typeof AdminCollectionsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gift-cards/': {
      id: '/admin/gift-cards/'
      path: '/gift-cards'
      fullPath: '/admin/gift-cards/'
      preLoaderRoute: typeof AdminGiftCardsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gift-cards/$id': {
      id: '/admin/gift-cards/$id'
      path: '/gift-cards/$id'
      fullPath: '/admin/gift-cards/$id'
      preLoaderRoute: typeof AdminGiftCardsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications/general': {
      id: '/admin/notifications/general'
      path: '/notifications/general'
      fullPath: '/admin/notifications/general'
      preLoaderRoute: typeof AdminNotificationsGeneralRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications/requests': {
      id: '/admin/notifications/requests'
      path: '/notifications/requests'
      fullPath: '/admin/notifications/requests'
      preLoaderRoute: typeof AdminNotificationsRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AccountRouteChildren {
  AccountOrdersIdRoute: typeof AccountOrdersIdRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountOrdersIdRoute: AccountOrdersIdRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminActivitiesRoute: typeof AdminActivitiesRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDiscountsRoute: typeof AdminDiscountsRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminPasskeysRoute: typeof AdminPasskeysRoute
  AdminPermanentWardrobeRoute: typeof AdminPermanentWardrobeRoute
  AdminShippingRoute: typeof AdminShippingRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCollectionsIdRoute: typeof AdminCollectionsIdRoute
  AdminCollectionsNewRoute: typeof AdminCollectionsNewRoute
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
  AdminGiftCardsIdRoute: typeof AdminGiftCardsIdRoute
  AdminNotificationsGeneralRoute: typeof AdminNotificationsGeneralRoute
  AdminNotificationsRequestsRoute: typeof AdminNotificationsRequestsRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminCollectionsIndexRoute: typeof AdminCollectionsIndexRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminGiftCardsIndexRoute: typeof AdminGiftCardsIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivitiesRoute: AdminActivitiesRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDiscountsRoute: AdminDiscountsRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminPasskeysRoute: AdminPasskeysRoute,
  AdminPermanentWardrobeRoute: AdminPermanentWardrobeRoute,
  AdminShippingRoute: AdminShippingRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCollectionsIdRoute: AdminCollectionsIdRoute,
  AdminCollectionsNewRoute: AdminCollectionsNewRoute,
  AdminCustomersIdRoute: AdminCustomersIdRoute,
  AdminGiftCardsIdRoute: AdminGiftCardsIdRoute,
  AdminNotificationsGeneralRoute: AdminNotificationsGeneralRoute,
  AdminNotificationsRequestsRoute: AdminNotificationsRequestsRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminCollectionsIndexRoute: AdminCollectionsIndexRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminGiftCardsIndexRoute: AdminGiftCardsIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ExchangesRoute: ExchangesRoute,
  FaqRoute: FaqRoute,
  GiftCardsRoute: GiftCardsRoute,
  LegalQuestionnaireRoute: LegalQuestionnaireRoute,
  OrderConfirmedRoute: OrderConfirmedRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRouteWithChildren,
  SizeGuideRoute: SizeGuideRoute,
  WishlistRoute: WishlistRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
